site_name: Literate Programming & Docker
site_author: Louis Moresi
site_dir: www

# theme over-ride

theme_dir: jupyter-server-theme

# Layout of pages

use_directory_urls: False
include_next_prev: False

# Theme
theme: flatly

pages:
- index.md
- Map.md
- About:
    - 'How to write a new page' : WritingContent.md
    - 'Installation instructions' : Instructions.md

# Mathematics

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/mathjax-local-config.js
